config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :abouts
  resources :programs
  resources :news


  root 'home#new'



  resources :home
  resource :admin
  resource :session


  get 'messages/new' => 'messages#new', as: 'new_message'
  post 'messages' => 'messages#create'


  get 'home/show' => 'home#show'
  get 'logout' => 'sessions#destroy'
  get 'admin/new' => 'admin#new'

  get 'sessions/create'

  get 'auth/:provider/callback' => 'admins#create', as: 'auth0_callback'
  get 'auth/auth0', as: 'auth0_login'
  get 'logout' => 'admins#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/program.rb
class Program < ApplicationRecord
  mount_uploader :image, ImageUploader

end

app/controllers/programs_controller.rb
class ProgramsController < ApplicationController
  before_action :set_program, only: [:show, :edit, :update, :destroy]
  # GET /programs
  # GET /programs.json
  def index
    @programs = Program.all
  end

  # GET /programs/1
  # GET /programs/1.json
  def show
  end

  # GET /programs/new
  def new
    @program = Program.new
  #   @program.image = params[:file]
  #
  #   @program.save!
  #   @program.image.url
  #   @program.image.current_path
  #   @program.image_identifier
  end

  # GET /programs/1/edit
  def edit
  end

  # POST /programs
  # POST /programs.json
  def create
    @program = Program.new(program_params)

    respond_to do |format|
      if @program.save
        format.html { redirect_to home_show_path, notice: 'Program was successfully created.' }
        format.json { render :show, status: :created, location: @program }
      else
        format.html { render :new }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /programs/1
  # PATCH/PUT /programs/1.json
  def update
    respond_to do |format|
      if @program.update(program_params)
        format.html { redirect_to @program, notice: 'Program was successfully updated.' }
        format.json { render :show, status: :ok, location: @program }
      else
        p "<>"*30
        p @program.errors
        format.html { render :edit }
        format.json { render json: @program.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /programs/1
  # DELETE /programs/1.json
  def destroy
    @program.destroy
    respond_to do |format|
      format.html { redirect_to home_show_path, notice: 'Program was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_program
      @program = Program.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def program_params
      params.require(:program).permit(:image, :title, :url, :description)
    end
end

app/helpers/programs_helper.rb
module ProgramsHelper
end

app/views/programs/_form.html.erb
<%= form_with(model: @program, remote: true) do |form| %>
  <% if @program.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(program.errors.count, "error") %> prohibited this program from being saved:</h2>

      <ul>
      <% program.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control-file"%>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url, class: "form-control" %>
  </div>

  <div class="description-field">
    <%= form.label :description %>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="actions">
    <%#= form.submit %>
  </div>
<% end %>

app/views/programs/_front-index.html.erb
<div class="programs-index-front-end" id="carouselControls">
  <div class="programs-front-end">
    <div class="program-slider">
      <div id="carouselIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselIndicators" data-slide-to="1"></li>
          <li data-target="#carouselIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel slide" data-ride="carousel">
            <div class="carousel-item active">
              <% @first_program = @programs[0] %>
              <% @programs_new = @programs.drop(1) %>
              <%= image_tag @first_program.image.url, class: "d-block w-100 image-front-program", alt: "city of miami program"%>
              <div class="carousel-caption">
                <h2><%= @first_program.title %></h2>
                <p class="d-none d-sm-block description"><%= @first_program.description %></p>
              </div>
            </div>
            <% @programs_new.each do |program|  %>
            <div class="carousel-item">
              <%= image_tag program.image.url, class: "d-block w-100 image-front-program", alt: "city of miami program"%>
              <div class="carousel-caption">
                <h2><%= program.title %></h2>
                <p class="d-none d-sm-block description"><%= program.description %></p>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
            <% end %>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/programs/_index.html.erb
<h1>Programs</h1>




<%= link_to 'Create New Program', new_program_path,  class: 'program-new', remote: true  %>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th class="image">Image</th>
      <th class="title-program">Title</th>
      <th class="url">Url</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @programs.each do |program| %>
      <tr>
        <td class="cms-img"><%= image_tag program.image.url, class: "cms-img img-fluid" %></td>
        <td><%= program.title %></td>
        <td><%= program.url %></td>
        <td><%= simple_format(program.description) %></td>
        <td class="show"><%= link_to 'Show', program, class: 'program-show', remote: true %></td>
        <td class="edit"><%= link_to 'Edit', edit_program_path(program), class: 'program-edit', remote: true %></td>
        <td class="destroy"><%= link_to 'Destroy', program, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/programs/_show.html.erb
<p>
  <strong>Image:</strong>
  <%= image_tag @program.image.url, class:"cms-img" %>
</p>

<p>
  <strong>Title:</strong>
  <%= @program.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @program.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @program.description %>
</p>

app/views/programs/edit.html.erb
<h1>Editing Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Show', @program %> |
<%= link_to 'Back', programs_path %>

app/views/programs/edit.js.erb
$(".modal-footer .btn-primary").show();
$('.modal-title').html("Editing Program");
$('.modal-body').html("<%= j render 'programs/form', program: @programs %>");
$('.modal').modal();

app/views/programs/index.html.erb
<div class="container">
<% @programs.each do |program|  %>
  <div class="carousel-item active ">

    <%= image_tag program.image.url, class: "d-block w-100"%>
    <div class="carousel-caption d-none d-md-block">
      <h5><%= program.title %></h5>
      <p><%= program.description %></p>

    </div>
  </div>
  <% end %>
</div>

app/views/programs/new.html.erb
<h1>New Program</h1>

<%= render 'form', program: @program %>

<%= link_to 'Back', programs_path %>

app/views/programs/new.js.erb
$(".modal-footer .btn-primary").show();
$('.modal-title').html("New Program");
$('.modal-body').html("<%= j render 'programs/form', program: @programs %>");
$('.modal').modal();

app/views/programs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= @program.image %>
</p>

<p>
  <strong>Title:</strong>
  <%= @program.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @program.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @program.description %>
</p>

<%= link_to 'Edit', edit_program_path(@program) %> |
<%= link_to 'Back', programs_path %>

app/views/programs/show.js.erb
$(".modal-footer .btn-primary").hide();
$('.modal-title').html("Preview Program");
$('.modal-body').html("<%= j render 'programs/show', program: @programs %>");
$('.modal').modal();