config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :abouts
  resources :programs
  resources :news


  root 'home#new'



  resources :home
  resource :admin
  resource :session


  get 'messages/new' => 'messages#new', as: 'new_message'
  post 'messages' => 'messages#create'


  get 'home/show' => 'home#show'
  get 'logout' => 'sessions#destroy'
  get 'admin/new' => 'admin#new'

  get 'sessions/create'

  get 'auth/:provider/callback' => 'admins#create', as: 'auth0_callback'
  get 'auth/auth0', as: 'auth0_login'
  get 'logout' => 'admins#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/news.rb
class News < ApplicationRecord

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action :set_news, only: [:show, :edit, :update, :destroy]
  # mount_uploader :image, ImageUploader
  # GET /news
  # GET /news.json
  def index
    @news_all = News.all
  end

  # GET /news/1
  # GET /news/1.json
  def show
  end

  # GET /news/new
  def new
    @news = News.new

  end

  # GET /news/1/edit
  def edit
  end

  # POST /news
  # POST /news.json
  def create
    response = MetaInspector.new(params[:url])

    @news = News.new(img: response.images.best, title: response.best_title, url: response.url, description: response.description)

    respond_to do |format|
      if @news.save
        format.html { redirect_to home_show_path, notice: 'News was successfully created.' }
        format.json { render :show, status: :created, location: @news }
      else
        format.html { render :new }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /news/1
  # PATCH/PUT /news/1.json
  def update
    respond_to do |format|
      if @news_all.update(news_params)
        format.html { redirect_to @news, notice: 'News was successfully updated.' }
        format.json { render :show, status: :ok, location: @news }
      else
        format.html { render :edit }
        format.json { render json: @news.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /news/1
  # DELETE /news/1.json
  def destroy
    @news.destroy
    respond_to do |format|
      format.html { redirect_to home_show_path, notice: 'News was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_news
      @news = News.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def news_params
      params.require(:news).permit(:img, :title, :url, :description)
    end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/views/news/_form.html.erb
<%= form_with(model: news, url:'/news', remote: true) do |form| %>
<%= form.text_field :url, class: "form-control"%>
  </div>
<% end %>

app/views/news/_front-index.html.erb
<div class= "front-news-index">
  <div class="card-columns">

    <% @news_all.reverse.each do |news|  %>

    <div class="card p-1 card-news-height" >

      <%= image_tag news.img, class: "card-img-top", alt: "News Image" %>

      <div class="card-body">

        <h4 class="card-title"><%= news.title %></h4>
        <p class="card-text"><%= news.description %></p>

        <%= link_to 'See Article', news.url, class: "btn btn-primary", id: "mayor-news-text", alt: "link to external news site" %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/news/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>News</h1>


<%= link_to 'New News', new_news_path, class: 'news-new', remote: true %>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Title</th>
      <th>Url</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @news_all.reverse.each do |news| %>
      <tr>
        <td class="cms-img"><%= image_tag news.img, class: "cms-img"%></td>
        <td><%= news.title %></td>
        <td><%= news.url %></td>
        <td><%= news.description %></td>
        <td><%= link_to 'Show', news, class: 'news-show', remote: true %></td>
        <td><%= link_to 'Edit', edit_news_path(news), class: 'news-edit', remote: true %></td>
        <td><%= link_to 'Destroy', news, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/news/_show.html.erb
<!-- <% @news_all.each do |news|  %>
<div class="card-group">
<div class="card" style="width: 18rem;">
  <%= image_tag news.img, class: "card-img-top", alt: "Card image cap" %>
  <div class="card-body">
    <h4 class="card-title"><%= news.title %></h4>
    <p class="card-text"><%= news.description %></p>
    <%= link_to 'See Article', news.url, class: "btn btn-primary", id: "mayor-news-text" %>
  </div>
  </div>
    <% end %>
</div> -->
<p>
  <strong>Image:</strong>
  <%= image_tag @news.image.url, class:"cms-img" %>
</p>

<p>
  <strong>Title:</strong>
  <%= @pnews.title %>
</p>

<p>
  <strong>Url:</strong>
  <%= @pnews.url %>
</p>

<p>
  <strong>Description:</strong>
  <%= @news.description %>
</p>

app/views/news/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Show', @news %> |
<%= link_to 'Back', news_index_path %>

app/views/news/edit.js.erb
$(".modal-footer .btn-primary").show();
$('.modal-title').html("Editing News");
$('.modal-body').html("<%= j render 'news/form', news: @news_all %>");
$('.modal').modal();

app/views/news/index.html.erb
<p id="notice"><%= notice %></p>


<div class="card-columns">
  <% @news_all.each do |news|  %>

  <div class="card p-1 card-news-height" style="width: 18rem;">
    <%= image_tag news.img, class: "card-img-top", alt: "Card image cap" %>
    <div class="card-body">
      <h4 class="card-title"><%= news.title %></h4>
      <p class="card-text"><%= news.description %></p>
      <%= link_to 'See Article', news.url, class: "btn btn-primary", id: "mayor-news-text" %>

    </div>

  </div>
  <br>
  <br>
  <% end %>
</div>

app/views/news/new.html.erb
<h1>New News</h1>

<%= render 'form', news: @news %>

<%= link_to 'Back', news_index_path %>

app/views/news/new.js.erb
$(".modal-footer .btn-primary").show();
$('.modal-title').html("New News");
$('.modal-body').html("<%= j render 'news/form', news: @news_all %>");
$('.modal').modal();

app/views/news/show.js.erb
$(".modal-footer .btn-primary").hide();
$('.modal-title').html("News Preview");
$('.modal-body').html("<%= j render 'news/show', news: @news %>");
$('.modal').modal();

app/views/news/shower.html.erb
<!-- <% render 'index' %> -->