config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :abouts
  resources :programs
  resources :news


  root 'home#new'



  resources :home
  resource :admin
  resource :session


  get 'messages/new' => 'messages#new', as: 'new_message'
  post 'messages' => 'messages#create'


  get 'home/show' => 'home#show'
  get 'logout' => 'sessions#destroy'
  get 'admin/new' => 'admin#new'

  get 'sessions/create'

  get 'auth/:provider/callback' => 'admins#create', as: 'auth0_callback'
  get 'auth/auth0', as: 'auth0_login'
  get 'logout' => 'admins#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end
  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to home_show_path, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to home_show_path, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :title, :email)
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_create.html.erb
<div class="rounded mx-auto d-block">
  You have successfully created a new contact!
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>
<% end %>

app/views/contacts/_front-index.html.erb
<div class= "contacts-index">
<div class="container">
  <ul class='row' id="contacts-ul">
    <% @contacts.each do |contact| %>
    <div class='col'>
      <li><b><%= contact.name %></li></b>
      <li ><%= contact.title %></li>
      <li ><%= link_to contact.email, new_message_path, class: 'contact-show', remote: true, alt: "link to send email" %></li>
      <br>
      <br>
    </div>
    <% end %>
  </ul>
</div>
</div>

app/views/contacts/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>
<%= link_to 'New Contact', new_contact_path, class: 'contact-new', remote: true %>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.title %></td>
        <td><%= contact.email %></td>
        <td><%= link_to 'Show', contact, class: 'contact-show', remote: true %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact), class: 'contact-edit', remote: true %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/contacts/_show.html.erb
<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Title:</strong>
  <%= @contact.title %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

app/views/contacts/create.html.erb
<div class="rounded mx-auto d-block">
  You have successfully created a new contact!
</div>

app/views/contacts/create.js.erb
$(".modal-footer .btn-primary").show();
$('.modal-title').html("New Contact");
$('.modal-body').html("<%= j render 'contacts/create', contact: @contact %>");
$('.modal').modal();

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/edit.js.erb
$(".modal-footer .btn-primary").show();
$('.modal-title').html("Editing About");
$('.modal-body').html("<%= j render 'contacts/form', contact: @contact %>");
$('.modal').modal();

app/views/contacts/index.html.erb
<div class= "contacts-index">
<div class="container">
  <ul class='row' id="contacts-ul">
    <% @contacts.each do |contact| %>
    <div class='col'>
      <li><b><%= contact.name %></li></b>
      <li ><%= contact.title %></li>
      <li ><%= contact.email %></li>
      <br>
      <br>
    </div>
    <% end %>
  </ul>
</div>
</div>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/new.js.erb
$(".modal-footer .btn-primary").show();
$('.modal-title').html("New Contact");
$('.modal-body').html("<%= j render 'contacts/form', contact: @contact %>");
$('.modal').modal();

app/views/contacts/show.html.erb
<%= render 'show' %>

app/views/contacts/show.js.erb
$(".modal-footer .btn-primary").hide();
$('.modal-title').html("Preview Contact");
$('.modal-body').html("<%= j render 'contacts/show', contact: @contacts %>");
$('.modal').modal();