config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  resources :abouts
  resources :programs
  resources :news


  root 'home#new'



  resources :home
  resource :admin
  resource :session


  get 'messages/new' => 'messages#new', as: 'new_message'
  post 'messages' => 'messages#create'


  get 'home/show' => 'home#show'
  get 'logout' => 'sessions#destroy'
  get 'admin/new' => 'admin#new'

  get 'sessions/create'

  get 'auth/:provider/callback' => 'admins#create', as: 'auth0_callback'
  get 'auth/auth0', as: 'auth0_login'
  get 'logout' => 'admins#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/about.rb
class About < ApplicationRecord
  mount_uploader :image, ImageUploader

end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController
  before_action :set_about, only: [:show, :edit, :update, :destroy]

  # GET /abouts
  # GET /abouts.json
  def index
    @abouts = About.all
  end

  # GET /abouts/1
  # GET /abouts/1.json
  def show

  end

  # GET /abouts/new
  def new
    @about = About.new
  end

  # GET /abouts/1/edit
  def edit
  end

  # POST /abouts
  # POST /abouts.json
  def create
    @about = About.new(about_params)

    respond_to do |format|
      if @about.save
        format.html { redirect_to home_show_path, notice: 'About was successfully created.' }
        format.json { render :show, status: :created, location: @about }
      else
        format.html { render :new }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /abouts/1
  # PATCH/PUT /abouts/1.json
  def update
    respond_to do |format|
      if @about.update(about_params)
        format.html { redirect_to @about, notice: 'About was successfully updated.' }
        format.json { render :show, status: :ok, location: @about }
      else
        format.html { render :edit }
        format.json { render json: @about.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /abouts/1
  # DELETE /abouts/1.json
  def destroy
    @about.destroy
    respond_to do |format|
      format.html { redirect_to home_show_path, notice: 'About was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_about
      @about = About.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def about_params
      params.require(:about).permit(:image, :text)
    end
end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/views/abouts/_form.html.erb
<%= form_with(model: about, remote: true) do |form| %>
  <% if about.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(about.errors.count, "error") %> prohibited this about from being saved:</h2>

      <ul>
      <% about.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, class: "form-control-file" %>
  </div>

  <div class="field">
    <%= form.label :text %>
    <%= form.text_area :text, class: "form-control" %>
  </div>

<% end %>

app/views/abouts/_front-index.html.erb
<div class="front-about-index">

  <div class="about-mayor-index">
    <% @abouts.each do |about| %>
    <div>
      <%= image_tag about.image.url, class: "sworn-in about-mayor-image" %>
    </div>
    <div class="mayor-about-text">
      <%= simple_format(about.text) %>
    </div>
    <% end %>
  </div>

</div>

app/views/abouts/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>About</h1>

<div class="new-about-link"><%= link_to 'New About', new_about_path, class: 'about-new', remote: true %></div>
<br>
<br>
<table class="table">
  <thead>
    <tr>
      <th>Image</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @abouts.each do |about| %>
      <tr>
        <td><%= image_tag about.image.url, class:"cms-img" %></td>
        <td><%= about.text %></td>
        <td><%= link_to 'Show', about, class: 'about-show', remote: true %></td>
        <td><%= link_to 'Edit', edit_about_path(about), class: 'about-edit', remote: true %></td>
        <td><%= link_to 'Destroy', about, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/abouts/_show.html.erb
<div class ="mayor-about-container">
  <%= image_tag @about.image.url, class: "sworn-in" %>
  <p class="mayor-about" id="mayor-about-body"><%= simple_format(@about.text) %></p>
</div>

app/views/abouts/edit.html.erb
<h1>Editing About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Show', @about %> |
<%= link_to 'Back', abouts_path %>

app/views/abouts/edit.js.erb
$(".modal-footer .btn-primary").show();
$('.modal-title').html("Editing About");
$('.modal-body').html("<%= j render 'abouts/form', about: @about %>");
$('.modal').modal();

app/views/abouts/front-index-programs.js.erb
$('.carousel').carousel({
  interval: 2000
})

app/views/abouts/index.html.erb
<div class="about-mayor-index">
<% @abouts.each do |about| %>
<%= image_tag about.image.url, class: "sworn-in" %>
<%= simple_format(about.text) %>
<% end %>
</div>

app/views/abouts/new.html.erb
<h1>New About</h1>

<%= render 'form', about: @about %>

<%= link_to 'Back', abouts_path %>

app/views/abouts/new.js.erb
$(".modal-footer .btn-primary").show();
$('.modal-title').html("New About");
$('.modal-body').html("<%= j render 'abouts/form', about: @about %>");
$('.modal').modal();

app/views/abouts/show.js.erb
$(".modal-footer .btn-primary").hide();
$('.modal-title').html("Preview About");
$('.modal-body').html("<%= j render 'abouts/show', about: @about %>");
$('.modal').modal();